name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Generate Test Certificate
        run: |
          New-SelfSignedCertificate -Type CodeSigningCert -Subject "CN=TestCertificate" -CertStoreLocation Cert:\LocalMachine\My
      
      - name: Build solution without signing
        run: msbuild -Restore /p:Configuration=Debug /p:Platform=x64 /p:DisableSigning=true
